theme: jekyll-theme-minimal

title:  Ranting Randomness
description: Gsoc student, julia, compilers and random stuff.
url:  http://dokfaust.github.io

author: Gaetano

future: true
timezone: UTC+2
plugins: [github-pages]
